"use client";
import { useEffect, useMemo, useState } from "react";
import { CheckoutMode } from "../lib/tebex/types";

type Product = { id:string; name:string; category:string; price:number; sale?:number; badge?:string; popular?:boolean; image:string; short:string; description:string; features:string[]; checkoutMode:CheckoutMode; tebexPackageId?:string; tebexDirectLink?:string; active:boolean };
type CartLine = Product & { qty:number };
const initial: Product[] = [
 {id:"mist-rank",name:"Mist Rank",category:"Ranks",price:8.99,sale:6.99,badge:"SALE",popular:true,image:"/images/products/mist-rank.png",short:"A gentle boost for your adventure.",description:"Unlock quality-of-life commands and a Mist rank prefix.",features:["/home slots","Colored chat prefix","Priority queue"],checkoutMode:"disabled",tebexPackageId:"YOUR_TEBEX_PACKAGE_ID",active:true},
 {id:"cloud-rank",name:"Cloud Rank",category:"Ranks",price:14.99,sale:11.99,badge:"20% OFF",image:"/images/products/cloud-rank.png",short:"More freedom above the clouds.",description:"Expanded survival perks for regular players.",features:["Extra homes","Cosmetics","Daily claim"],checkoutMode:"disabled",active:true},
 {id:"frost-rank",name:"Frost Rank",category:"Ranks",price:24.99,image:"/images/products/frost-rank.png",short:"Premium survival perks.",description:"A cool collection of premium features.",features:["More claims","Frost tag","Priority support"],checkoutMode:"disabled",active:true},
 {id:"ice-rank",name:"Ice Rank",category:"Ranks",price:39.99,image:"/images/products/ice-rank.png",short:"The ultimate MistSMP rank.",description:"Our largest rank package.",features:["All rank perks","Exclusive cosmetics","More homes"],checkoutMode:"disabled",active:true},
 {id:"mist-coins",name:"Mist Coins",category:"Coins",price:4.99,sale:3.99,badge:"SALE",image:"/images/products/mist-coins.png",short:"Spend coins in the server shop.",description:"A flexible coin pack.",features:["Instant balance credit","Use in /shop"],checkoutMode:"disabled",active:true},
 {id:"starter-bundle",name:"Starter Bundle",category:"Bundles",price:12.99,image:"/images/products/starter-bundle.png",short:"Begin your survival story well.",description:"Essentials for a new world.",features:["Tools","Food","Cosmetic crate"],checkoutMode:"disabled",active:true},
 {id:"survival-key",name:"Survival Crate Key",category:"Crate Keys",price:2.49,image:"/images/products/survival-key.png",short:"Try your luck at spawn.",description:"One key for the Survival crate.",features:["One crate key","Random reward"],checkoutMode:"disabled",active:true},
 {id:"premium-key",name:"Premium Crate Key",category:"Crate Keys",price:5.99,image:"/images/products/premium-key.png",short:"Premium crate rewards.",description:"One key for the Premium crate.",features:["One premium key","Rare reward pool"],checkoutMode:"disabled",active:true},
 {id:"seasonal-bundle",name:"Seasonal Bundle",category:"Seasonal",price:19.99,sale:15.99,badge:"LIMITED",image:"/images/products/seasonal-bundle.png",short:"A limited seasonal collection.",description:"Available while the season lasts.",features:["Seasonal cosmetics","Crate keys","Coin bonus"],checkoutMode:"disabled",active:true}
];
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
export default function Store(){
 const [products,setProducts]=useState(initial),[cart,setCart]=useState<CartLine[]>([]),[tab,setTab]=useState("All"),[query,setQuery]=useState(""),[sort,setSort]=useState("Featured"),[selected,setSelected]=useState<Product|undefined>(),[cartOpen,setCartOpen]=useState(false),[account,setAccount]=useState(""),[gift,setGift]=useState(""),[giftMode,setGiftMode]=useState(false),[admin,setAdmin]=useState(false),[notice,setNotice]=useState(""),[saleIndex,setSaleIndex]=useState(0);
 const announcements=["MISTSM P SUMMER SALE · Up to 30% off selected items","WELCOME TO MISTSM P · Support the survival community"];
 useEffect(()=>{const t=setInterval(()=>setSaleIndex(n=>(n+1)%announcements.length),5000);return()=>clearInterval(t)},[]);
 const categories=["All","Ranks","Coins","Crate Keys","Bundles","Seasonal"];
 const list=useMemo(()=>products.filter(p=>p.active&&(tab==="All"||p.category===tab)&&`${p.name} ${p.short} ${p.description} ${p.category}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="Price: Low to High"?(a.sale??a.price)-(b.sale??b.price):sort==="Price: High to Low"?(b.sale??b.price)-(a.sale??a.price):sort==="On Sale"?(Number(Boolean(b.sale))-Number(Boolean(a.sale))):0),[products,tab,query,sort]);
 const add=(p:Product)=>{if(!account&&!giftMode){setNotice("Enter a Minecraft username before adding items.");return}setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});setNotice(`${p.name} added to your cart.`);setSelected(undefined)};
 const total=cart.reduce((s,p)=>s+(p.sale??p.price)*p.qty,0), retail=cart.reduce((s,p)=>s+p.price*p.qty,0); const update=(id:string,d:number)=>setCart(c=>c.flatMap(i=>i.id===id&&i.qty+d<=0?[]:i.id===id?[{...i,qty:i.qty+d}]:[i]));
 return <main><div className="sale">✦ {announcements[saleIndex]} <button onClick={()=>setSaleIndex((saleIndex+1)%2)}>›</button><button onClick={()=>setNotice("Announcement hidden for this demo session.")}>×</button></div>
 <header><a className="brand" href="#store"><span>✦</span><b>MistSMP</b><small>OFFICIAL STORE</small></a><nav>{["Store","Ranks","Coins","Crate Keys","Bundles","Top Donors","Support"].map(x=><a key={x} href={x==="Support"?"#support":"#store"}>{x}</a>)}</nav><div className="tools"><button className="server" onClick={()=>{navigator.clipboard?.writeText("play.mistsmp.net");setNotice("Server IP copied to clipboard.")}}><i/> ONLINE <strong>play.mistsmp.net</strong></button><button onClick={()=>document.getElementById("account")?.scrollIntoView()}>Account</button><button onClick={()=>setCartOpen(true)}>Cart <em>{cart.reduce((s,x)=>s+x.qty,0)}</em></button></div></header>
 <section id="account" className="account"><div><b>Minecraft account</b><span>Enter your username to add perks to your basket.</span></div><input aria-label="Minecraft username" value={account} onChange={e=>setAccount(e.target.value.replace(/[^a-zA-Z0-9_]/g,"").slice(0,16))} placeholder="Enter your EXACT username"/><button onClick={()=>setNotice(account.length>=3?`Demo account ready: ${account}`:"Use 3–16 letters, numbers, or underscores.")}>Verify & log in</button><button className={giftMode?"active":""} onClick={()=>{setGiftMode(!giftMode);if(!giftMode)setGift("")}}>🎁 Gift purchases</button></section>
 {giftMode&&<section className="gift"><b>Gifting Mode Active</b><span>All items in your cart will be purchased for:</span><input value={gift} onChange={e=>setGift(e.target.value.replace(/[^a-zA-Z0-9_]/g,"").slice(0,16))} placeholder="Friend's Minecraft username"/><button onClick={()=>setNotice(gift.length>=3?`Gifts will be prepared for ${gift}.`:"Use a valid friend username.")}>Verify friend</button><button onClick={()=>setGiftMode(false)}>Cancel</button></section>}
 <section id="store" className="store-head"><p>SERVER SHOP / SURVIVAL SMP</p><h1>MistSMP Store</h1><span>Support the Survival SMP and unlock in-game perks.</span><label>Search <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products"/></label></section>
 <section className="categories">{categories.map(c=><button key={c} className={tab===c?"selected":""} onClick={()=>setTab(c)}>{c}</button>)}<select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}>{["Featured","Popular","Newest","Price: Low to High","Price: High to Low","On Sale"].map(x=><option key={x}>{x}</option>)}</select></section>
 <section className="grid">{list.map(p=><article className="product" key={p.id}><div className="image">{p.badge&&<mark>{p.badge}</mark>}<span>✦</span><small>{p.image}</small></div><div className="product-body"><p>{p.category}</p><h2>{p.name}{p.popular&&<em>POPULAR</em>}</h2><span>{p.short}</span><div><strong>{money(p.sale??p.price)}</strong>{p.sale&&<del>{money(p.price)}</del>}<button onClick={()=>setSelected(p)}>View</button></div></div></article>)}</section>
 {!list.length&&<div className="empty">No products matched your search. Try another category or phrase.</div>}
 <section id="support" className="support"><div><p>NEED HELP WITH A PURCHASE?</p><h2>We’re here to help.</h2><span>Contact us on Discord and include your Minecraft username when requesting support.</span></div><a href="https://discord.gg/mistsmp" target="_blank" rel="noreferrer">Join Discord</a><div><b>Refund Policy</b><span>Digital-item policies are configurable before launch. Do not make purchases until the production store policies are published.</span></div></section>
 <footer><div className="brand"><span>✦</span><b>MistSMP</b><small>OFFICIAL SURVIVAL SMP STORE</small></div><div><b>Store</b><a href="#store">Ranks</a><a href="#store">Coins</a><a href="#store">Crate Keys</a><a href="#store">Bundles</a></div><div><b>Information</b><a href="#support">Support</a><a href="#">Terms</a><a href="#">Privacy</a><a href="#">Refund Policy</a></div><div><b>Server</b><span>play.mistsmp.net</span><button onClick={()=>{navigator.clipboard?.writeText("play.mistsmp.net");setNotice("Server IP copied.")}}>Copy IP</button></div><button className="admin-link" onClick={()=>setAdmin(true)}>Demo Admin</button></footer>
 <div className="mobile-nav"><a href="#store">Home</a><a href="#store">Store</a><button onClick={()=>document.querySelector<HTMLInputElement>(".store-head input")?.focus()}>Search</button><button onClick={()=>setCartOpen(true)}>Cart ({cart.length})</button><button onClick={()=>document.getElementById("account")?.scrollIntoView()}>Account</button></div>
 {selected&&<div className="overlay" role="dialog" aria-modal="true"><section className="modal"><button className="close" onClick={()=>setSelected(undefined)}>×</button><div className="detail-image">✦<small>{selected.image}</small></div><p>{selected.category}</p><h2>{selected.name}</h2><span>{selected.description}</span><ul>{selected.features.map(f=><li key={f}>{f}</li>)}</ul><strong>{money(selected.sale??selected.price)}</strong>{selected.sale&&<del>{money(selected.price)}</del>}<aside>Automatic in-game delivery after payment integration.</aside><button className="primary" onClick={()=>add(selected)}>Add to cart</button><button onClick={()=>{add(selected);setCartOpen(true)}}>Buy now</button></section></div>}
 {cartOpen&&<div className="overlay" role="dialog" aria-modal="true"><section className="drawer"><button className="close" onClick={()=>setCartOpen(false)}>×</button><p>YOUR CART</p><h2>Cart {cart.length?`(${cart.reduce((s,x)=>s+x.qty,0)})`:"is empty"}</h2>{cart.map(x=><div className="line" key={x.id}><div><b>{x.name}</b><small>{money(x.sale??x.price)}</small></div><button onClick={()=>update(x.id,-1)}>−</button><span>{x.qty}</span><button onClick={()=>update(x.id,1)}>+</button><button onClick={()=>update(x.id,-x.qty)}>Remove</button></div>)}{cart.length>0&&<><input placeholder="Gift Card / Coupon (demo only)" onFocus={()=>setNotice("Coupons require a future Tebex configuration.")}/><div className="totals"><span>Subtotal <b>{money(retail)}</b></span><span>Discount <b>−{money(retail-total)}</b></span><strong>Total <b>{money(total)}</b></strong></div><label className="terms"><input type="checkbox"/> I agree to the Terms and Refund Policy.</label><button className="primary" onClick={()=>setNotice("Tebex checkout is not configured yet. Add a secure server-side configuration or provider direct link.")}>Proceed to checkout</button></>}<button onClick={()=>setCartOpen(false)}>Continue shopping</button></section></div>}
 {admin&&<Admin products={products} setProducts={setProducts} close={()=>setAdmin(false)}/>} {notice&&<div className="toast" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}</main> }
function Admin({products,setProducts,close}:{products:Product[],setProducts:(p:Product[])=>void,close:()=>void}){const [name,setName]=useState("");return <div className="overlay admin" role="dialog" aria-modal="true"><section><button className="close" onClick={close}>×</button><p>DEMO ADMIN MODE</p><h2>Storefront manager</h2><span>Authentication and production database persistence are not connected.</span><div className="stats"><b>{products.length}<small>Total products</small></b><b>{products.filter(p=>p.active).length}<small>Active products</small></b><b>{products.filter(p=>p.sale).length}<small>On sale</small></b><b>2<small>Announcements</small></b></div><h3>Products</h3><input value={name} onChange={e=>setName(e.target.value)} placeholder="New product name"/><button onClick={()=>name&&setProducts([...products,{...initial[0],id:crypto.randomUUID(),name,active:true}])}>Create product</button><div className="admin-list">{products.map(p=><div key={p.id}><b>{p.name}</b><span>{p.category} · {money(p.sale??p.price)}</span><button onClick={()=>setProducts(products.map(x=>x.id===p.id?{...x,active:!x.active}:x))}>{p.active?"Deactivate":"Activate"}</button><button onClick={()=>setProducts(products.filter(x=>x.id!==p.id))}>Delete</button></div>)}</div><h3>Settings & announcements</h3><p>Server name, IP, social links, notices, pricing and Tebex configuration are designed as centralized demo data for a future authenticated backend.</p></section></div>}
